cultures:
  - name: "global"
    categories:
      - name: "positive"
        phrases:
          - "I like"
          - "we like"
          - "seems good"
          - "seems gd"
          - "looks good"
          - "looks gd"
          - "not bad"
          - "I'm ok with"
          - "I'm ok w/"
          - "it's ok"
          - "I agree"
          - "I support"
          - "we support"
          - "that's a good idea"
          - "that's a gd idea"
          - "good one"
          - "gd one"
          - "good 1"
          - "it's terrific"
          - "awesome"
          - "awsme"
          - "that's great"
          - "good idea"
          - "gd idea"
          - "brilliant"
          - "outstanding"
          - "is beautiful"
          - "glorious"
          - "I really like"
          - "I love"
          - "congrats"
          - "congratulations"
      - name: "negative"
        phrases:
          - "I dislike"
          - "I don't like"
          - "I dont like"
          - "we dislike"
          - "we don't like"
          - "we dont like"
          - "seems bad"
          - "looks bad"
          - "not good"
          - "not gd"
          - "I'm not ok with"
          - "I'm not ok w/"
          - "it's not ok"
          - "I disagree"
          - "bad one"
          - "bad 1"
          - "it's terrible"
          - "awful"
          - "sucks"
          - "bad idea"
          - "is stupid"
          - "it's stupid"
          - "its stupid"
          - "is ugly"
          - "it's ugly"
          - "its ugly"
          - "what an idiot"
          - "go to hell"
          - "I hate"
          - "shut up"
  - name: "panama"
    categories:
      - name: "meGusta"
        phrases:
          - "me gusta"
          - "nos gusta"
          - "me parece bien"
          - "me parece"
          - "nos parece bien"
          - "no me parece mal"
          - "no nos parece mal"
          - "no le parece mal"
          - "le parece bien"
          - "estoy de acuerdo"
          - "toy de acuerdo"
          - "lo apoyo"
          - "lo apoyamos"
          - "estoy contigo"
          - "toy contigo"
          - "estamos contigo"
          - "tamos contigo"
          - "buena esa"
          - "me agrada"
          - "mucho mejor"
          - "es mejor"
          - "es mucho mejor"
          - "es lo mejor"
          - "la boto"
          - "la botaron con"
          - "esta del carajo"
          - "ta del carajo"
          - "esta cool"
          - "ta cool"
          - "felicidades"
          - "para que respete"
          - "pa que respete"
          - "tiene la capacidad"
          - "buen trabajo"
          - "excelente"
      - name: "noMeGusta"
        phrases:
          - "no me gusta"
          - "no nos gusta"
          - "rechazo"
          - "sinverguenza"
          - "sin verguenza"
          - "es un sinverguenza"
          - "es 1 sinverguenza"
          - "es un sin verguenza"
          - "es 1 sin verguenza"
          - "es una sinverguenza"
          - "es una sin verguenza"
          - "ignorante"
          - "es un ignorante"
          - "es 1 ignorante"
          - "es una ignorante"
          - "no me parece bien"
          - "nos parece bien"
          - "me parece mal"
          - "no le parece bien"
          - "le parece mal"
          - "nos parece mal"
          - "no estoy de acuerdo"
          - "no toy en de acuerdo"
          - "no lo apoyo"
          - "no lo apoyamos"
          - "no estoy contigo"
          - "no toy contigo"
          - "no estamos contigo"
          - "no tamos contigo"
          - "mala esa"
          - "no me agrada"
          - "no le agrada"
          - "no nos agrada"
          - "mucho peor"
          - "es peor"
          - "es mucho peor"
          - "no sirve"
          - "no tiene la capacidad"
          - "es una porqueria"
          - "que porkeria"
          - "q porkeria"
          - "que porqueria"
          - "q porqueria"
          - "es una porkeria"
          - "es 1 porkeria"
          - "es una mierda"
          - "es 1 mierda"
          - "que asco"
          - "q asco"
          - "asco me da"
          - "me da asco"
          - "me kbrea"
          - "me kabrea"
          - "me cabrea"
          - "vale cebo"
          - "me enchucha"
          - "es un perron"
          - "es 1 perron"
          - "respeta HP"
          - "fallaron ahi"
          - "fallaron hay"
          - "fallaron ai"
          - "fallo ai"
          - "fallo hay"
          - "fallo ahi"
          - "no esta al nivel"
          - "mentiroso"
          - "mentirosa"
          - "es un mentiroso"
          - "es 1 mentiroso"
          - "es una mentirosa"
          - "es 1 mentirosa"
          - "abusibo"
          - "es un abusivo"
          - "es un abusibo"
          - "es 1 abusivo"
          - "es 1 abusibo"
          - "abusivo"
          - "abusiba"
          - "abusiva"
          - "es una abusiva"
          - "es una abusiba"
          - "es 1 abusiva"
          - "es 1 abusiba"
          - "sucio"
          - "es un sucio"
          - "es 1 sucio"
          - "sucia"
          - "es una sucia"
          - "es 1 sucia"
          - "vago"
          - "vagos"
          - "es un vago"
          - "es 1 vago"
          - "son unos vagos"
          - "inepto"
          - "ineptos"
      - name: "ofensivo"
        phrases:
          - "vale verga"
          - "esa vaina vale verga"
          - "no vale ni verga"
          - "que huevo"
          - "que webo"
          - "q huevo"
          - "que webo"
          - "vale pinga"
          - "no vale ni pinga"
          - "q awebazon"
          - "que awebazon"
          - "que awebason"
          - "q awebason"
          - "es un awebao"
          - "es 1 awebao"
          - "xuxa de su madre"
          - "chucha de su madre"
          - "es un hijo de puta"
          - "es un hijueputa"
          - "es una puta"
          - "es 1 puta"
          - "es un idiota"
          - "es una idiota"
          - "es 1 idiota"
          - "es un imbecil"
          - "es una imbecil"
          - "es 1 imbecil"
          - "es una perra"
          - "es 1 perra"
          - "es una zorra"
          - "es 1 zorra"
          - "ladron"
          - "es un ladron"
          - "es una ladrona"
          - "es 1 ladron"
          - "es 1 ladrona"
          - "chupalo"
          - "xupalo"
          - "callate obeso"
          - "callate obesa"
          - "callate maricon"
          - "callate hijo de puta"
          - "callate hijueputa"