cultures:
  - name: "global"
    categories:
      - name: "like"
        phrases:
          - "I like"
          - "we like"
          - "seems good"
          - "looks good"
          - "not bad"
          - "I'm ok with"
          - "it's ok"
          - "I agree"
          - "I support"
          - "we support"
          - "that's a good idea"
          - "good one"
          - "it's terrific"
          - "awesome"
          - "that's great"
          - "good idea"
          - "brilliant"
          - "outstanding"
          - "is beautiful"
          - "glorious"
          - "I really like it"
          - "I love"
      - name: "dislike"
        phrases:
          - "I dislike"
          - "I don't like"
          - "I dont like"
          - "we dislike"
          - "we don't like"
          - "we dont like"
          - "seems bad"
          - "looks bad"
          - "not good"
          - "I'm not ok with"
          - "it's not ok"
          - "I disagree"
          - "bad one"
          - "it's terrible"
          - "awful"
          - "sucks"
          - "bad idea"
          - "is stupid"
          - "is ugly"
          - "what an idiot"
          - "go to hell"
          - "I hate"
  - name: "panama"
    categories:
      - name: "me gusta"
        phrases:
          - "me gusta"
          - "nos gusta"
          - "me parece bien"
          - "nos parece bien"
          - "no me parece mal"
          - "no nos parece mal"
          - "estoy de acuerdo"
          - "toy de acuerdo"
          - "lo apoyo"
          - "lo apoyamos"
          - "estoy contigo"
          - "toy contigo"
          - "estamos contigo"
          - "tamos contigo"
          - "buena esa"
          - "me agrada"
          - "mucho mejor"
          - "es mejor"
          - "es mucho mejor"
          - "la boto"
          - "la botaron con"
          - "esta del carajo"
          - "ta del carajo"
      - name: "no me gusta"
        phrases:
          - "no me gusta"
          - "no nos gusta"
          - "no me parece bien"
          - "nos parece bien"
          - "me parece mal"
          - "nos parece mal"
          - "no estoy de acuerdo"
          - "no toy en de acuerdo"
          - "no lo apoyo"
          - "no lo apoyamos"
          - "no estoy contigo"
          - "no toy contigo"
          - "no estamos contigo"
          - "no tamos contigo"
          - "mala esa"
          - "no me agrada"
          - "mucho peor"
          - "es peor"
          - "es mucho peor"
          - "no sirve"
          - "es una porqueria"
          - "es una porkeria"
          - "es una mierda"
          - "que asco"
          - "q asco"
          - "me kbrea"
          - "me kabrea"
          - "me cabrea"
          - "vale cebo"
      - name: "ofensivo"
        phrases:
          - "vale verga"
          - "esa vaina vale verga"
          - "no vale ni verga"
          - "vale pinga"
          - "no vale ni pinga"
          - "q awebazon"
          - "que awebazon"
          - "es un awebao"
          - "xuxa de su madre"
          - "chucha de su madre"
          - "es un hijo de puta"
          - "es un hijueputa"
          - "es una puta"
          - "es un idiota"
          - "es un imbecil"
          - "es una perra"
          - "es una zorra"
          - "chupalo"
          - "xupalo"